# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frontend\ui_templates\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 300)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\frontend\\ui_templates\\../../../../../../../../Users/wieckla/Downloads/p-logo-no-background.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_exit = QtWidgets.QPushButton(self.centralwidget)
        self.bt_exit.setGeometry(QtCore.QRect(530, 220, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.bt_exit.setFont(font)
        self.bt_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_exit.setStyleSheet("/* General Exit Button Style */\n"
"QPushButton {\n"
"    background-color: #e74c3c;    /* Red background for the button */\n"
"    color: white;                 /* White text color */\n"
"    border: 2px solid #c0392b;    /* Darker red border */\n"
"    border-radius: 8px;           /* Rounded corners for the button */\n"
"    padding: 10px 20px;           /* Padding inside the button */\n"
"    font-size: 16px;              /* Font size for the button text */\n"
"    font-weight: bold;            /* Bold text for emphasis */\n"
"    text-align: center;           /* Center the text inside the button */\n"
"}\n"
"\n"
"/* Hover State */\n"
"QPushButton:hover {\n"
"    background-color: #c0392b;    /* Darker red background on hover */\n"
"    border: 2px solid #a93226;    /* Even darker red border on hover */\n"
"    color: #ecf0f1;               /* Light text color on hover */\n"
"}\n"
"\n"
"/* Pressed State */\n"
"QPushButton:pressed {\n"
"    background-color: #a93226;    /* Even darker red background when pressed */\n"
"    border: 2px solid #922b21;    /* Dark border when pressed */\n"
"    color: #bdc3c7;               /* Grey text color when pressed */\n"
"}\n"
"\n"
"/* Disabled State */\n"
"QPushButton:disabled {\n"
"    background-color: #bdc3c7;    /* Light grey background when disabled */\n"
"    border: 2px solid #95a5a6;    /* Grey border when disabled */\n"
"    color: #7f8c8d;               /* Grey text color when disabled */\n"
"}\n"
"")
        self.bt_exit.setObjectName("bt_exit")
        self.lb_select_fuel_type = QtWidgets.QLabel(self.centralwidget)
        self.lb_select_fuel_type.setGeometry(QtCore.QRect(20, 20, 161, 31))
        self.lb_select_fuel_type.setStyleSheet("/* General Label Style */\n"
"QLabel {\n"
"    font-size: 18px;             /* Base font size for regular labels */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db; ;              /* Dark grey text color */\n"
"    padding: 4px;               /* Padding around the text */\n"
"    border: 1px solid transparent; /* Optional border for spacing */\n"
"}\n"
"\n"
"/* Prominent Headline Style */\n"
"QLabel.headline {\n"
"    font-size: 24px;            /* Larger font size for prominent headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db;             /* Distinct blue color for headlines */\n"
"    padding: 8px;               /* Increased padding for a more spacious look */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    background-color: #f0f8ff;  /* Light blue background to make the headline stand out */\n"
"    border-radius: 4px;         /* Slightly rounded corners for a modern appearance */\n"
"    margin-bottom: 12px;        /* Space below the headline to separate from other elements */\n"
"}\n"
"\n"
"/* Subheadline Style */\n"
"QLabel.subheadline {\n"
"    font-size: 18px;            /* Slightly smaller than headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #2c3e50;             /* Dark grey color for subheadlines */\n"
"    padding: 6px;               /* Padding around the text */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    margin-bottom: 8px;         /* Space below the subheadline */\n"
"}\n"
"\n"
"/* Disabled Label Style */\n"
"QLabel:disabled {\n"
"    color: #7f8c8d;             /* Grey text color for disabled state */\n"
"}\n"
"")
        self.lb_select_fuel_type.setObjectName("lb_select_fuel_type")
        self.lb_default_alarm_type = QtWidgets.QLabel(self.centralwidget)
        self.lb_default_alarm_type.setGeometry(QtCore.QRect(20, 110, 191, 31))
        self.lb_default_alarm_type.setStyleSheet("/* General Label Style */\n"
"QLabel {\n"
"    font-size: 18px;             /* Base font size for regular labels */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db; ;              /* Dark grey text color */\n"
"    padding: 4px;               /* Padding around the text */\n"
"    border: 1px solid transparent; /* Optional border for spacing */\n"
"}\n"
"\n"
"/* Prominent Headline Style */\n"
"QLabel.headline {\n"
"    font-size: 24px;            /* Larger font size for prominent headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db;             /* Distinct blue color for headlines */\n"
"    padding: 8px;               /* Increased padding for a more spacious look */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    background-color: #f0f8ff;  /* Light blue background to make the headline stand out */\n"
"    border-radius: 4px;         /* Slightly rounded corners for a modern appearance */\n"
"    margin-bottom: 12px;        /* Space below the headline to separate from other elements */\n"
"}\n"
"\n"
"/* Subheadline Style */\n"
"QLabel.subheadline {\n"
"    font-size: 18px;            /* Slightly smaller than headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #2c3e50;             /* Dark grey color for subheadlines */\n"
"    padding: 6px;               /* Padding around the text */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    margin-bottom: 8px;         /* Space below the subheadline */\n"
"}\n"
"\n"
"/* Disabled Label Style */\n"
"QLabel:disabled {\n"
"    color: #7f8c8d;             /* Grey text color for disabled state */\n"
"}\n"
"")
        self.lb_default_alarm_type.setObjectName("lb_default_alarm_type")
        self.cb_fuel_type = QtWidgets.QComboBox(self.centralwidget)
        self.cb_fuel_type.setGeometry(QtCore.QRect(40, 60, 131, 31))
        self.cb_fuel_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_fuel_type.setStyleSheet("/* General Combo Box Style */\n"
"QComboBox {\n"
"    font-size: 14px;              /* Font size for the text */\n"
"    color: #2c3e50;               /* Text color */\n"
"    padding: 4px;                 /* Padding inside the combo box */\n"
"    border: 2px solid #2980b9;    /* Blue border for the combo box */\n"
"    border-radius: 4px;           /* Rounded corners for the combo box */\n"
"    background-color: #ecf0f1;    /* Light grey background */\n"
"}\n"
"\n"
"/* Arrow Indicator (the dropdown arrow) */\n"
"QComboBox::drop-down {\n"
"    width: 20px;                  /* Size of the dropdown arrow area */\n"
"    border-left: 2px solid #2980b9;/* Left border to separate the arrow */\n"
"    background-color: #3498db;    /* Blue background for the dropdown arrow */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(frontend/ui_templates/down_arrow.png);  /* Custom arrow icon */\n"
"    width: 12px;                /* Size of the arrow */\n"
"    height: 12px;\n"
"}\n"
"\n"
"\n"
"/* Combo Box when the dropdown is open */\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #2980b9;   /* Blue border around the dropdown list */\n"
"    background-color: #ecf0f1;   /* Light grey background for the dropdown list */\n"
"    selection-background-color: #3498db; /* Blue background for selected items */\n"
"    selection-color: white;      /* White text for selected items */\n"
"}\n"
"\n"
"")
        self.cb_fuel_type.setObjectName("cb_fuel_type")
        self.cb_fuel_type.addItem("")
        self.cb_fuel_type.addItem("")
        self.cb_fuel_type.addItem("")
        self.cb_fuel_type.addItem("")
        self.cb_fuel_type.addItem("")
        self.cb_fuel_type.addItem("")
        self.te_default_alarm_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.te_default_alarm_time.setGeometry(QtCore.QRect(40, 150, 131, 31))
        self.te_default_alarm_time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.te_default_alarm_time.setStyleSheet("/* General Time Edit Style */\n"
"QTimeEdit {\n"
"    font-size: 14px;               /* Font size */\n"
"    color: #2c3e50;                /* Text color */\n"
"    padding: 4px;                  /* Padding */\n"
"    border: 2px solid #2980b9;     /* Blue border */\n"
"    border-radius: 4px;            /* Rounded corners */\n"
"    background-color: #ecf0f1;     /* Light grey background */\n"
"}\n"
"\n"
"/* Time Edit Buttons (Up and Down Arrow Area) */\n"
"QTimeEdit::up-button, QTimeEdit::down-button {\n"
"    width: 18px;                   /* Size of the button area */\n"
"    border: none;                  /* No border */\n"
"    background-color: #3498db;     /* Blue background */\n"
"}\n"
"\n"
"QTimeEdit::up-arrow {\n"
"    width: 10px;                   /* Arrow size */\n"
"    height: 10px;\n"
"    image: url(frontend/ui_templates/up_arrow.png);  /* Custom arrow icon */\n"
"}\n"
"\n"
"QTimeEdit::down-arrow {\n"
"    width: 10px;                   /* Arrow size */\n"
"    height: 10px;\n"
"    image: url(frontend/ui_templates/down_arrow.png);  /* Custom arrow icon */\n"
"}\n"
"\n"
"/* Hover Effect for Time Edit */\n"
"QTimeEdit:hover {\n"
"    border-color: #3498db;         /* Change border color on hover */\n"
"}\n"
"")
        self.te_default_alarm_time.setAlignment(QtCore.Qt.AlignCenter)
        self.te_default_alarm_time.setObjectName("te_default_alarm_time")
        self.te_default_sleep_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.te_default_sleep_time.setGeometry(QtCore.QRect(40, 240, 131, 31))
        self.te_default_sleep_time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.te_default_sleep_time.setStyleSheet("/* General Time Edit Style */\n"
"QTimeEdit {\n"
"    font-size: 14px;               /* Font size */\n"
"    color: #2c3e50;                /* Text color */\n"
"    padding: 4px;                  /* Padding */\n"
"    border: 2px solid #2980b9;     /* Blue border */\n"
"    border-radius: 4px;            /* Rounded corners */\n"
"    background-color: #ecf0f1;     /* Light grey background */\n"
"}\n"
"\n"
"/* Time Edit Buttons (Up and Down Arrow Area) */\n"
"QTimeEdit::up-button, QTimeEdit::down-button {\n"
"    width: 18px;                   /* Size of the button area */\n"
"    border: none;                  /* No border */\n"
"    background-color: #3498db;     /* Blue background */\n"
"}\n"
"\n"
"QTimeEdit::up-arrow {\n"
"    width: 10px;                   /* Arrow size */\n"
"    height: 10px;\n"
"    image: url(frontend/ui_templates/up_arrow.png);  /* Custom arrow icon */\n"
"}\n"
"\n"
"QTimeEdit::down-arrow {\n"
"    width: 10px;                   /* Arrow size */\n"
"    height: 10px;\n"
"    image: url(frontend/ui_templates/down_arrow.png);  /* Custom arrow icon */\n"
"}\n"
"\n"
"/* Hover Effect for Time Edit */\n"
"QTimeEdit:hover {\n"
"    border-color: #3498db;         /* Change border color on hover */\n"
"}\n"
"")
        self.te_default_sleep_time.setAlignment(QtCore.Qt.AlignCenter)
        self.te_default_sleep_time.setObjectName("te_default_sleep_time")
        self.lb_default_alarm_type_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_default_alarm_type_2.setGeometry(QtCore.QRect(20, 200, 191, 31))
        self.lb_default_alarm_type_2.setStyleSheet("/* General Label Style */\n"
"QLabel {\n"
"    font-size: 18px;             /* Base font size for regular labels */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db; ;              /* Dark grey text color */\n"
"    padding: 4px;               /* Padding around the text */\n"
"    border: 1px solid transparent; /* Optional border for spacing */\n"
"}\n"
"\n"
"/* Prominent Headline Style */\n"
"QLabel.headline {\n"
"    font-size: 24px;            /* Larger font size for prominent headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db;             /* Distinct blue color for headlines */\n"
"    padding: 8px;               /* Increased padding for a more spacious look */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    background-color: #f0f8ff;  /* Light blue background to make the headline stand out */\n"
"    border-radius: 4px;         /* Slightly rounded corners for a modern appearance */\n"
"    margin-bottom: 12px;        /* Space below the headline to separate from other elements */\n"
"}\n"
"\n"
"/* Subheadline Style */\n"
"QLabel.subheadline {\n"
"    font-size: 18px;            /* Slightly smaller than headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #2c3e50;             /* Dark grey color for subheadlines */\n"
"    padding: 6px;               /* Padding around the text */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    margin-bottom: 8px;         /* Space below the subheadline */\n"
"}\n"
"\n"
"/* Disabled Label Style */\n"
"QLabel:disabled {\n"
"    color: #7f8c8d;             /* Grey text color for disabled state */\n"
"}\n"
"")
        self.lb_default_alarm_type_2.setObjectName("lb_default_alarm_type_2")
        self.lb_alarm_text = QtWidgets.QLabel(self.centralwidget)
        self.lb_alarm_text.setGeometry(QtCore.QRect(280, 20, 181, 41))
        self.lb_alarm_text.setStyleSheet("/* General Label Style */\n"
"QLabel {\n"
"    font-size: 18px;             /* Base font size for regular labels */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db; ;              /* Dark grey text color */\n"
"    padding: 4px;               /* Padding around the text */\n"
"    border: 1px solid transparent; /* Optional border for spacing */\n"
"}\n"
"\n"
"/* Prominent Headline Style */\n"
"QLabel.headline {\n"
"    font-size: 24px;            /* Larger font size for prominent headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db;             /* Distinct blue color for headlines */\n"
"    padding: 8px;               /* Increased padding for a more spacious look */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    background-color: #f0f8ff;  /* Light blue background to make the headline stand out */\n"
"    border-radius: 4px;         /* Slightly rounded corners for a modern appearance */\n"
"    margin-bottom: 12px;        /* Space below the headline to separate from other elements */\n"
"}\n"
"\n"
"/* Subheadline Style */\n"
"QLabel.subheadline {\n"
"    font-size: 18px;            /* Slightly smaller than headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #2c3e50;             /* Dark grey color for subheadlines */\n"
"    padding: 6px;               /* Padding around the text */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    margin-bottom: 8px;         /* Space below the subheadline */\n"
"}\n"
"\n"
"/* Disabled Label Style */\n"
"QLabel:disabled {\n"
"    color: #7f8c8d;             /* Grey text color for disabled state */\n"
"}\n"
"")
        self.lb_alarm_text.setObjectName("lb_alarm_text")
        self.bt_speech_to_text = QtWidgets.QPushButton(self.centralwidget)
        self.bt_speech_to_text.setGeometry(QtCore.QRect(300, 230, 131, 41))
        self.bt_speech_to_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_speech_to_text.setStyleSheet("/* General Button Style */\n"
"QPushButton {\n"
"    font-size: 14px;               /* Font size */\n"
"    color: #ffffff;                /* White text color */\n"
"    padding: 6px 12px;             /* Padding around the text */\n"
"    border: 2px solid #2980b9;     /* Blue border */\n"
"    border-radius: 4px;            /* Rounded corners */\n"
"    background-color: #3498db;     /* Blue background */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;     /* Darker blue background on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f618d;     /* Even darker blue when pressed */\n"
"    border-color: #1f618d;         /* Darker border on press */\n"
"}\n"
"")
        self.bt_speech_to_text.setObjectName("bt_speech_to_text")
        self.lb_alarm = QtWidgets.QLabel(self.centralwidget)
        self.lb_alarm.setGeometry(QtCore.QRect(470, 20, 181, 41))
        self.lb_alarm.setStyleSheet("/* General Label Style */\n"
"QLabel {\n"
"    font-size: 18px;             /* Base font size for regular labels */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db; ;              /* Dark grey text color */\n"
"    padding: 4px;               /* Padding around the text */\n"
"    border: 1px solid transparent; /* Optional border for spacing */\n"
"}\n"
"\n"
"/* Prominent Headline Style */\n"
"QLabel.headline {\n"
"    font-size: 24px;            /* Larger font size for prominent headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #3498db;             /* Distinct blue color for headlines */\n"
"    padding: 8px;               /* Increased padding for a more spacious look */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    background-color: #f0f8ff;  /* Light blue background to make the headline stand out */\n"
"    border-radius: 4px;         /* Slightly rounded corners for a modern appearance */\n"
"    margin-bottom: 12px;        /* Space below the headline to separate from other elements */\n"
"}\n"
"\n"
"/* Subheadline Style */\n"
"QLabel.subheadline {\n"
"    font-size: 18px;            /* Slightly smaller than headlines */\n"
"    font-weight: bold;          /* Bold text for emphasis */\n"
"    color: #2c3e50;             /* Dark grey color for subheadlines */\n"
"    padding: 6px;               /* Padding around the text */\n"
"    border: none;               /* No border for a cleaner look */\n"
"    margin-bottom: 8px;         /* Space below the subheadline */\n"
"}\n"
"\n"
"/* Disabled Label Style */\n"
"QLabel:disabled {\n"
"    color: #7f8c8d;             /* Grey text color for disabled state */\n"
"}\n"
"")
        self.lb_alarm.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_alarm.setObjectName("lb_alarm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " "))
        self.bt_exit.setText(_translate("MainWindow", "Exit"))
        self.lb_select_fuel_type.setText(_translate("MainWindow", "Select Fuel Type"))
        self.lb_default_alarm_type.setText(_translate("MainWindow", "Default Alarm Time"))
        self.cb_fuel_type.setItemText(0, _translate("MainWindow", "Super E10", "super_e10"))
        self.cb_fuel_type.setItemText(1, _translate("MainWindow", "Super E5"))
        self.cb_fuel_type.setItemText(2, _translate("MainWindow", "Super Plus"))
        self.cb_fuel_type.setItemText(3, _translate("MainWindow", "Diesel"))
        self.cb_fuel_type.setItemText(4, _translate("MainWindow", "LKW Diesel"))
        self.cb_fuel_type.setItemText(5, _translate("MainWindow", "LPG"))
        self.lb_default_alarm_type_2.setText(_translate("MainWindow", "Default Sleep Time"))
        self.lb_alarm_text.setText(_translate("MainWindow", "Alarm gesetzt für:"))
        self.bt_speech_to_text.setText(_translate("MainWindow", "Speech to Text"))
        self.lb_alarm.setText(_translate("MainWindow", "00:00 Uhr"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
