name: Build
on:
  push:
    branches:
      - '*'  # Run on push to any branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your required Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest pytest-cov

      # Set environment variables
      - name: Set environment variables
        run: |
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> $GITHUB_ENV

      # Run tests
      - name: Run tests
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          python -m unittest discover -p "*_test.py"
        continue-on-error: false  # Fail the job if tests fail

      # Run tests with coverage
      - name: Run tests with coverage
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          coverage run -m unittest discover -p "*_test.py"
          coverage xml -o coverage.xml

      # Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your required Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest pytest-cov

      # Download coverage report artifact
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: .

      # Verify coverage.xml (optional but recommended)
      - name: Verify coverage.xml
        run: |
          ls -la
          cat coverage.xml || echo "coverage.xml not found"

      # SonarCloud Scan step
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master  # Use a specific stable version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.x
            -Dsonar.verbose=true  # Enable verbose logging for debugging
